[project]
name = "glamira-crawl-product"
version = "0.1.0"
description = ""
authors = [
    {name = "Thanh Nguyen",email = "marncguy4n@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "certifi==2026.7.22",
    "cffi==2.1.1",
    "curl-cffi==0.16.0",
    "dnspython==2.8.0",
    "ip2location==8.11.0",
    "pycparser==3.0",
    "pymongo==4.17.0",
    "python-dotenv==1.2.2",
    "pyyaml==6.0.3",
    "google-cloud-storage (>=3.13.0,<4.0.0)",
    "pyarrow (>=25.0.0,<26.0.0)",
]

[project.scripts]
glamira-crawl = "glamira_crawl.cli:main"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "glamira_crawl"}]
